WHITESPACE = _{ " " | "\t" }

alpha = { 'a'..'z' | 'A'..'Z' | "." | "-" | "_" | "\"" | "/" | "*" | "$" | "^" | "@" }
digit = { '0'..'9' }

ident = @{ (alpha | digit)+ }
ident_list = @{ !digit ~ ident ~ (" " ~ ident)+ }

wildcard = { ident ~ "=" ~ (ident | ident_list)+ }

target_line = { ident ~ ":" ~ (ident|ident_list)* }

build_command = @{ ident_list }

remake_file = {
    SOI ~
    ((wildcard | target_line | build_command)? ~ NEWLINE)* ~
    EOI
}