WHITESPACE = _{ " " | "\t" }

alpha = { 'a'..'z' | 'A'..'Z' | "." | "-" | "_" | "\"" }
digit = { '0'..'9' }

ident = @{ (alpha | digit)+ }
symbol = @{ (alpha | digit)+ }
ident_list = @{ !digit ~ ident ~ (" " ~ ident)+ }

wildcard = { symbol ~ "=" ~ (ident | ident_list)+ }

target_line = { symbol ~ ":" ~ (ident)+ }

build_command = @{ ident_list }

remake_file = {
    SOI ~
    ((wildcard | target_line | build_command)? ~ NEWLINE)* ~
    EOI
}