WHITESPACE = _{ " " | "\t" }

alpha = { 'a'..'z' | 'A'..'Z' | "." | "-" | "_" }
digit = { '0'..'9' }

ident = @{ (alpha | digit)+ }
symbol = @{ (alpha | digit)+ }
ident_list = @{ !digit ~ ident ~ (" " ~ ident)+ }

wildcard = { symbol ~ "=" ~ (ident | ident_list)+ }

target_line = { symbol ~ ":" ~ (ident)+ ~ NEWLINE }

build_command = {ident_list ~ NEWLINE? }

build_command_list = { (build_command)+ }

rule = { target_line ~ build_command_list+ }